### ISSUE TITLE
[request] ability to upload files to select rooms

### ISSUE THREAD

**Issue by bamtan** [kadranel/python-volafile-downloader#2]
Thanks for fixing the spaces issue!

This is a feature request for having the ability to upload files to a select room. Since a config.py file is present, having the ability to upload to a room with an account would be great, too.

volapi has an upload.py example here: https://github.com/volafiled/python-volapi/blob/master/docs/examples/upload.py

**Comment by kadranel** [comment]
Hey, since i didnt really want to clutter this repository with additional stuff, that is not necessarily downloading from volafile i created some other repositories to help you with that:

- https://github.com/kadranel/python-volafile-uploader
This is basically the equivalent to the current downloader for uploading, also uses the config.py for the user setting. If you just want to copy the uploader.py into your folder from there or use this as a standalone tool you are fine.

- https://github.com/kadranel/python-volafile-tools
Use this, if you want to keep the 2 features together like you suggested here. This may grow with further features though, so i can not really guarantee, that the config.py will always stay compatible with a previous version. For now you can use your current config though.

If you have further questions regarding these "changes" feel free to ask in here! I'll keep this issue in the back of my mind for the next few days. 😃

Best regards
kad

**Comment by bamtan** [comment]
This is perfect, thank you so much kad! 😄
